version: '3'
services:
  app:
    image: amirrhkm/kokohub-api:latest
    container_name: kokohub-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./database:/var/www/database
    networks:
      - kokohub

  nginx:
    image: nginx:alpine
    container_name: kokohub-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - kokohub

networks:
  kokohub:
    driver: bridge
